// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBh5Pk9_TwbY-D6g0YLxCENVslBYjAxqrw',
    appId: '1:143045145814:web:054d3461ab0e1956b30577',
    messagingSenderId: '143045145814',
    projectId: 'portfolio-e4dc9',
    authDomain: 'portfolio-e4dc9.firebaseapp.com',
    storageBucket: 'portfolio-e4dc9.firebasestorage.app',
    measurementId: 'G-2Y0SKSBJJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCV2shkRXfcSsmCxn29P5h_I0YlZzp27sI',
    appId: '1:143045145814:android:c6bc3623abc86acbb30577',
    messagingSenderId: '143045145814',
    projectId: 'portfolio-e4dc9',
    storageBucket: 'portfolio-e4dc9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcE3c4FbTiSMAuHfLfKM-9BirAETGieoU',
    appId: '1:143045145814:ios:9b737c35aea2082ab30577',
    messagingSenderId: '143045145814',
    projectId: 'portfolio-e4dc9',
    storageBucket: 'portfolio-e4dc9.firebasestorage.app',
    iosBundleId: 'com.example.portfolioWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcE3c4FbTiSMAuHfLfKM-9BirAETGieoU',
    appId: '1:143045145814:ios:9b737c35aea2082ab30577',
    messagingSenderId: '143045145814',
    projectId: 'portfolio-e4dc9',
    storageBucket: 'portfolio-e4dc9.firebasestorage.app',
    iosBundleId: 'com.example.portfolioWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBh5Pk9_TwbY-D6g0YLxCENVslBYjAxqrw',
    appId: '1:143045145814:web:e8f2c2a815b2089eb30577',
    messagingSenderId: '143045145814',
    projectId: 'portfolio-e4dc9',
    authDomain: 'portfolio-e4dc9.firebaseapp.com',
    storageBucket: 'portfolio-e4dc9.firebasestorage.app',
    measurementId: 'G-132GQMCVT0',
  );
}
